import { orlovskiReels } from '../assets/home-images/orlovski/orlovskiReels.jsx';
import { Reels } from '../assets/home-images/reel/Reels.jsx';

const allCoverPhotos = {
  1: import.meta.glob("../assets/home-images/impress/cover/*.{webp,WEBP}", { eager: true }),
  2: import.meta.glob("../assets/home-images/desire/cover/*.{webp,WEBP}", { eager: true }),
  3: import.meta.glob("../assets/home-images/reel/cover/*.{webp,WEBP}", { eager: true }),
  4: import.meta.glob("../assets/home-images/etude/cover/*.{webp,WEBP}", { eager: true }),
  5: import.meta.glob("../assets/home-images/ppk/cover/*.{webp,WEBP}", { eager: true }),
  6: import.meta.glob("../assets/home-images/kate/cover/*.{webp,WEBP}", { eager: true }),
  7: import.meta.glob("../assets/home-images/sabine/cover/*.{webp,WEBP}", { eager: true }),
  8: import.meta.glob("../assets/home-images/veronica/cover/*.{webp,WEBP}", { eager: true }),
  9: import.meta.glob("../assets/home-images/veronicaPortrait/cover/*.{webp,WEBP}", { eager: true }),
  10: import.meta.glob("../assets/home-images/various/cover/*.{webp,WEBP}", { eager: true }),
  11: import.meta.glob("../assets/home-images/hanba/cover/*.{webp,WEBP}", { eager: true }),
  12: import.meta.glob("../assets/home-images/pilotka/cover/*.{webp,WEBP}", { eager: true }),
  13: import.meta.glob("../assets/home-images/orlovski/cover/*.{webp,WEBP}", { eager: true }),
  14: import.meta.glob("../assets/home-images/looks/cover/*.{webp,WEBP}", { eager: true }),
  15: import.meta.glob("../assets/home-images/agatta/cover/*.{webp,WEBP}", { eager: true }),
  16: import.meta.glob("../assets/home-images/depth/cover/*.{webp,WEBP}", { eager: true }),
  17: import.meta.glob("../assets/home-images/lucia/cover/*.{webp,WEBP}", { eager: true }),
  18: import.meta.glob("../assets/home-images/twhe/cover/*.{webp,WEBP}", { eager: true }),
  19: import.meta.glob("../assets/home-images/klucz/cover/*.{webp,WEBP}", { eager: true }),
  20: import.meta.glob("../assets/home-images/arualis/cover/*.{webp,WEBP}", { eager: true }),
  21: import.meta.glob("../assets/home-images/llis/cover/*.{webp,WEBP}", { eager: true }),
  22: import.meta.glob("../assets/home-images/laura/cover/*.{webp,WEBP}", { eager: true }),
  23: import.meta.glob("../assets/home-images/dancingKing/cover/*.{webp,WEBP}", { eager: true }),
  24: import.meta.glob("../assets/home-images/amelia/cover/*.{webp,WEBP}", { eager: true }),
  25: import.meta.glob("../assets/home-images/ada/cover/*.{webp,WEBP}", { eager: true }),
  26: import.meta.glob("../assets/home-images/business/cover/*.{webp,WEBP}", { eager: true }),
  27: import.meta.glob("../assets/home-images/together/cover/*.{webp,WEBP}", { eager: true }),
  28: import.meta.glob("../assets/home-images/mens/cover/*.{webp,WEBP}", { eager: true }),
  29: import.meta.glob("../assets/home-images/kozminalia/cover/*.{webp,WEBP}", { eager: true }),
  30: import.meta.glob("../assets/home-images/soWhat/cover/*.{webp,WEBP}", { eager: true }),
  31: import.meta.glob("../assets/home-images/dybala/cover/*.{webp,WEBP}", { eager: true }),
};

const allSessionPhotos = {
  1: import.meta.glob("../assets/home-images/impress/session/*.{webp,WEBP}", { eager: true }),
  2: import.meta.glob("../assets/home-images/desire/session/*.{webp,WEBP}", { eager: true }),
  3: import.meta.glob("../assets/home-images/reel/session/*.{webp,WEBP}", { eager: true }),
  4: import.meta.glob("../assets/home-images/etude/session/*.{webp,WEBP}", { eager: true }),
  5: import.meta.glob("../assets/home-images/ppk/session/*.{webp,WEBP}", { eager: true }),
  6: import.meta.glob("../assets/home-images/kate/session/*.{webp,WEBP}", { eager: true }),
  7: import.meta.glob("../assets/home-images/sabine/session/*.{webp,WEBP}", { eager: true }),
  8: import.meta.glob("../assets/home-images/veronica/session/*.{webp,WEBP}", { eager: true }),
  9: import.meta.glob("../assets/home-images/veronicaPortrait/session/*.{webp,WEBP}", { eager: true }),
  10: import.meta.glob("../assets/home-images/various/session/*.{webp,WEBP}", { eager: true }),
  11: import.meta.glob("../assets/home-images/hanba/session/*.{webp,WEBP}", { eager: true }),
  12: import.meta.glob("../assets/home-images/pilotka/session/*.{webp,WEBP}", { eager: true }),
  13: import.meta.glob("../assets/home-images/orlovski/session/*.{webp,WEBP}", { eager: true }),
  14: import.meta.glob("../assets/home-images/looks/session/*.{webp,WEBP}", { eager: true }),
  15: import.meta.glob("../assets/home-images/agatta/session/*.{webp,WEBP}", { eager: true }),
  16: import.meta.glob("../assets/home-images/depth/session/*.{webp,WEBP}", { eager: true }),
  17: import.meta.glob("../assets/home-images/lucia/session/*.{webp,WEBP}", { eager: true }),
  18: import.meta.glob("../assets/home-images/twhe/session/*.{webp,WEBP}", { eager: true }),
  19: import.meta.glob("../assets/home-images/klucz/session/*.{webp,WEBP}", { eager: true }),
  20: import.meta.glob("../assets/home-images/arualis/session/*.{webp,WEBP}", { eager: true }),
  21: import.meta.glob("../assets/home-images/llis/session/*.{webp,WEBP}", { eager: true }),
  22: import.meta.glob("../assets/home-images/laura/session/*.{webp,WEBP}", { eager: true }),
  23: import.meta.glob("../assets/home-images/dancingKing/session/*.{webp,WEBP}", { eager: true }),
  24: import.meta.glob("../assets/home-images/amelia/session/*.{webp,WEBP}", { eager: true }),
  25: import.meta.glob("../assets/home-images/ada/session/*.{webp,WEBP}", { eager: true }),
  26: import.meta.glob("../assets/home-images/business/session/*.{webp,WEBP}", { eager: true }),
  27: import.meta.glob("../assets/home-images/together/session/*.{webp,WEBP}", { eager: true }),
  28: import.meta.glob("../assets/home-images/mens/session/*.{webp,WEBP}", { eager: true }),
  29: import.meta.glob("../assets/home-images/soWhat/session/*.{webp,WEBP}", { eager: true }),
};

const allDescriptions = {
  1: import.meta.glob("../assets/home-images/desire/opis.txt", { as: 'raw', eager: true }),
  2: import.meta.glob("../assets/home-images/etude/opis.txt", { as: 'raw', eager: true }),
  3: import.meta.glob("../assets/home-images/ppk/opis.txt", { as: 'raw', eager: true }),
  4: import.meta.glob("../assets/home-images/hanba/opis.txt", { as: 'raw', eager: true }),
  5: import.meta.glob("../assets/home-images/pilotka/opis.txt", { as: 'raw', eager: true }),
  6: import.meta.glob("../assets/home-images/lucia/opis.txt", { as: 'raw', eager: true }),
  7: import.meta.glob("../assets/home-images/twhe/opis.txt", { as: 'raw', eager: true }),
  8: import.meta.glob("../assets/home-images/klucz/opis.txt", { as: 'raw', eager: true }),
  9: import.meta.glob("../assets/home-images/dancingKing/opis.txt", { as: 'raw', eager: true }),
  10: import.meta.glob("../assets/home-images/kozminalia/opis.txt", { as: 'raw', eager: true }),
  11: import.meta.glob("../assets/home-images/soWhat/opis.txt", { as: 'raw', eager: true }),
  12: import.meta.glob("../assets/home-images/dybala/opis.txt", { as: 'raw', eager: true }),
};

const allCasts = {
  1: import.meta.glob("../assets/home-images/impress/cast.txt", { as: 'raw', eager: true }),
  2: import.meta.glob("../assets/home-images/desire/cast.txt", { as: 'raw', eager: true }),
  3: import.meta.glob("../assets/home-images/reel/cast.txt", { as: 'raw', eager: true }),
  4: import.meta.glob("../assets/home-images/etude/cast.txt", { as: 'raw', eager: true }),
  5: import.meta.glob("../assets/home-images/ppk/cast.txt", { as: 'raw', eager: true }),
  6: import.meta.glob("../assets/home-images/kate/cast.txt", { as: 'raw', eager: true }),
  7: import.meta.glob("../assets/home-images/sabine/cast.txt", { as: 'raw', eager: true }),
  8: import.meta.glob("../assets/home-images/veronica/cast.txt", { as: 'raw', eager: true }),
  9: import.meta.glob("../assets/home-images/veronicaPortrait/cast.txt", { as: 'raw', eager: true }),
  10: import.meta.glob("../assets/home-images/various/cast.txt", { as: 'raw', eager: true }),
  11: import.meta.glob("../assets/home-images/hanba/cast.txt", { as: 'raw', eager: true }),
  12: import.meta.glob("../assets/home-images/pilotka/cast.txt", { as: 'raw', eager: true }),
  13: import.meta.glob("../assets/home-images/orlovski/cast.txt", { as: 'raw', eager: true }),
  14: import.meta.glob("../assets/home-images/looks/cast.txt", { as: 'raw', eager: true }),
  15: import.meta.glob("../assets/home-images/agatta/cast.txt", { as: 'raw', eager: true }),
  16: import.meta.glob("../assets/home-images/depth/cast.txt", { as: 'raw', eager: true }),
  17: import.meta.glob("../assets/home-images/lucia/cast.txt", { as: 'raw', eager: true }),
  18: import.meta.glob("../assets/home-images/twhe/cast.txt", { as: 'raw', eager: true }),
  19: import.meta.glob("../assets/home-images/klucz/cast.txt", { as: 'raw', eager: true }),
  20: import.meta.glob("../assets/home-images/arualis/cast.txt", { as: 'raw', eager: true }),
  21: import.meta.glob("../assets/home-images/llis/cast.txt", { as: 'raw', eager: true }),
  22: import.meta.glob("../assets/home-images/laura/cast.txt", { as: 'raw', eager: true }),
  23: import.meta.glob("../assets/home-images/dancingKing/cast.txt", { as: 'raw', eager: true }),
  24: import.meta.glob("../assets/home-images/amelia/cast.txt", { as: 'raw', eager: true }),
  25: import.meta.glob("../assets/home-images/ada/cast.txt", { as: 'raw', eager: true }),
};

const loadImages = (id) => {
  const sessionPhotos = allSessionPhotos[id] || {};
  const images = Object.values(sessionPhotos).map((mod) => mod.default);

  images.sort((a, b) => {
    const nameA = a.split('/').pop();
    const nameB = b.split('/').pop();
    return nameA.localeCompare(nameB, undefined, { numeric: true });
  });

  return images;
};

const loadCovers = (id) => {
  const coverPhotos = allCoverPhotos[id] || {};
  return Object.values(coverPhotos).map((mod) => mod.default);
};

const loadDescriptions = (id) => {
  const desc = allDescriptions[id] || {};
  return Object.values(desc)[0] || "";
};

const loadCasts = (id) => {
  const casts = allCasts[id] || {};
  return Object.values(casts)[0] || "";
}

export const getPhotos = () => {
  return [
    {
      id: 31,
      type: "media",
      title: "ADVERTISING SPOT",
      alt: "ADVERTISING SPOT",
      visible: '1',
      covers: loadCovers(31).map((img, index) => ({ id: index, img })),
      size: "cover",
      content: [],
      reels: [],
      trailer: "https://vimeo.com/1139027329",
      desc: loadDescriptions(12),
      casts: [],
      gridAreas: [
        "1 / 1 / 2 / 3",
        "1 / 3 / 2 / 5",
        "2 / 1 / 3 / 3",
        "2 / 3 / 3 / 5",
        "3 / 2 / 4 / 4",
        "4 / 1 / 5 / 3",
        "4 / 3 / 5 / 5",
        "5 / 2 / 6 / 4",
        "6 / 1 / 7 / 3",
        "6 / 3 / 7 / 5",
        "7 / 2 / 8 / 4",
      ]
    },
    {
      id: 30,
      type: "media",
      title: "so.what",
      alt: "so.what session images",
      visible: '1',
      covers: loadCovers(30).map((img, index) => ({ id: index, img })),
      size: "cover",
      content: loadImages(29).map((img, index) => ({ id: index + 1, img })),
      reels: [],
      trailer: "https://vimeo.com/1139023921",
      desc: loadDescriptions(11),
      casts: [],
      gridAreas: [
        "1 / 1 / 2 / 3",
        "1 / 3 / 2 / 5",
        "2 / 1 / 3 / 3",
        "2 / 3 / 3 / 5",
        "3 / 2 / 4 / 4",
        "4 / 1 / 5 / 3",
        "4 / 3 / 5 / 5",
        "5 / 2 / 6 / 4",
        "6 / 1 / 7 / 3",
        "6 / 3 / 7 / 5",
        "7 / 2 / 8 / 4",
      ]
    },
    {
      id: 29,
      type: "media",
      title: "KOŹMINALIA 2025 AFTERMOVIE",
      alt: "KOŹMINALIA 2025 AFTERMOVIE",
      visible: '0',
      covers: loadCovers(29).map((img, index) => ({ id: index, img })),
      size: "100% 100%",
      content: [],
      reels: [],
      trailer: "https://vimeo.com/1109829272",
      desc: loadDescriptions(10),
      gridAreas: [
      ]
    },
    {
      id: 28,
      type: "media",
      title: "klucz",
      alt: "Klucz session images",
      visible: '1',
      covers: loadCovers(19).map((img, index) => ({ id: index, img })),
      size: "cover",
      backgroundPosition: "10%",
      content: loadImages(19).map((img, index) => ({ id: index + 1, img })),
      reels: [],
      trailer: 'https://www.youtube.com/watch?v=cr7GEXDW0I4',
      desc: loadDescriptions(8),
      casts: loadCasts(19),
      gridAreas: [
        "1 / 1 / 2 / 4",
        "1 / 4 / 2 / 7",
        "2 / 1 / 3 / 4",
        "2 / 4 / 3 / 7",
        "3 / 1 / 4 / 4",
        "3 / 4 / 4 / 7",
        "4 / 1 / 5 / 3",
        "4 / 3 / 5 / 5",
        "4 / 5 / 5 / 7",
        "5 / 2 / 6 / 6",
        "6 / 1 / 7 / 4",
        "6 / 4 / 7 / 7",
        "7 / 1 / 8 / 4",
        "7 / 4 / 8 / 7",
      ],
    },
    {
      id: 27,
      type: "media",
      title: "twhe",
      alt: "TWHE session images",
      visible: '0',
      covers: loadCovers(18).map((img, index) => ({ id: index, img })),
      size: "100% 100%",
      content: loadImages(18).map((img, index) => ({ id: index + 1, img })),
      reels: [],
      trailer: 'https://vimeo.com/1059503029',
      desc: loadDescriptions(7),
      casts: loadCasts(18),
      gridAreas: [
        "1 / 1 / 2 / 2",
        "1 / 2 / 2 / 3",
        "2 / 1 / 3 / 3",
        "3 / 1 / 4 / 2",
        "3 / 2 / 4 / 3",
        "4 / 1 / 5 / 3",
        "5 / 1 / 6 / 2",
        "5 / 2 / 6 / 3",
        "6 / 1 / 7 / 2",
        "6 / 2 / 7 / 3",
      ],
    },
    {
      id: 26,
      type: "media",
      title: "Lucia",
      alt: "Lucia session images",
      visible: '0',
      covers: loadCovers(17).map((img, index) => ({ id: index, img })),
      size: "125% 125%",
      content: loadImages(17).map((img, index) => ({ id: index + 1, img })),
      reels: [],
      trailer: 'https://www.youtube.com/watch?v=9qDjTeGghuw',
      desc: loadDescriptions(6),
      casts: loadCasts(17),
      gridAreas: [
        "1 / 1 / 2 / 3",
        "2 / 1 / 3 / 2",
        "2 / 2 / 3 / 3",
        "3 / 1 / 4 / 3",
        "4 / 1 / 5 / 2",
        "4 / 2 / 5 / 3",
        "5 / 1 / 6 / 2",
        "5 / 2 / 6 / 3",
        "6 / 1 / 7 / 2",
        "6 / 2 / 7 / 3",
      ],
    },
    {
      id: 25,
      type: "media",
      title: "Dancing king",
      alt: "Dancing King session images",
      visible: '0',
      covers: loadCovers(23).map((img, index) => ({ id: index, img })),
      size: "cover",
      content: loadImages(23).map((img, index) => ({ id: index + 1, img })),
      reels: [],
      trailer: "https://youtu.be/yx4xuyx-mPc?si=S9wzaspL5QpqeRf7",
      desc: loadDescriptions(9),
      casts: loadCasts(23),
      gridAreas: [
        "1 / 1 / 2 / 2",
        "1 / 2 / 2 / 3",
        "2 / 1 / 3 / 3",
        "3 / 1 / 4 / 3",
        "4 / 1 / 5 / 2",
        "4 / 2 / 5 / 3",
      ]
    },
    {
      id: 24,
      type: "media",
      title: "pilotka",
      alt: "Pilotka session images",
      visible: '0',
      covers: loadCovers(12).map((img, index) => ({ id: index, img })),
      size: "cover",
      content: loadImages(12).map((img, index) => ({ id: index + 1, img })),
      reels: [],
      trailer: 'https://vimeo.com/862664791',
      desc: loadDescriptions(5),
      casts: loadCasts(12),
      gridAreas: [
        "1 / 1 / 2 / 4",
        "1 / 4 / 2 / 7",
        "2 / 1 / 3 / 5",
        "2 / 5 / 3 / 7",
        "3 / 1 / 4 / 3",
        "3 / 3 / 4 / 7",
        "4 / 2 / 5 / 6",
        "5 / 1 / 6 / 4",
        "5 / 4 / 6 / 7",
        "6 / 1 / 7 / 5",
        "6 / 5 / 7 / 7",
        "7 / 1 / 8 / 7",
      ]
    },
    {
      id: 23,
      type: "media",
      title: "hanba",
      alt: "Hanba session images",
      visible: '0',
      covers: loadCovers(11).map((img, index) => ({ id: index, img })),
      size: "cover",
      content: loadImages(11).map((img, index) => ({ id: index + 1, img })),
      reels: [],
      trailer: 'https://youtu.be/hGhN1PpaLFg?si=ohX9E0TBmPk-vuos',
      desc: loadDescriptions(4),
      casts: loadCasts(11),
      gridAreas: [
        "1 / 1 / 2 / 3",
        "2 / 1 / 3 / 2",
        "2 / 2 / 3 / 3",
      ]
    },
    {
      id: 22,
      type: "photos",
      title: "orlovski",
      alt: "Orlovski session images",
      visible: '0',
      covers: loadCovers(13).map((img, index) => ({ id: index, img })),
      size: "cover",    
      content: orlovskiReels,
      reels: [],
      trailer: [],
      casts: loadCasts(13),
      gridAreas: []
    },
    {
      id: 21,
      type: 'f',
      title: "polski problem kosmiczny",
      alt: "Polski Problem Kosmiczny session images",
      visible: '1',
      covers: loadCovers(5).map((img, index) => ({ id: index, img })),
      size: "cover",
      content: [],
      reels: [],
      trailer: 'https://www.youtube.com/watch?v=3_d4xK22bCI',
      desc: loadDescriptions(3),
      casts: loadCasts(5),
      gridAreas: [],
    },
    {
      id: 20,
      type: "media",
      title: "desire",
      alt: "Desire session images",
      visible: '1',
      covers: loadCovers(2).map((img, index) => ({ id: index, img })),
      size: "cover",
      content: loadImages(2).map((img, index) => ({ id: index + 1, img })),
      reels: [],
      trailer: 'https://vimeo.com/931685429',
      desc: loadDescriptions(1),
      casts: loadCasts(2),
      gridAreas: [
        "1 / 1 / 2 / 7",
        "2 / 1 / 3 / 7",
        "3 / 1 / 4 / 3",
        "3 / 3 / 4 / 5",
        "3 / 5 / 4 / 7",
        "4 / 1 / 5 / 4",
        "4 / 4 / 5 / 7",
      ],
    },
    {
      id: 19,
      type: "photos",
      title: "MEN'S SESSION",
      alt: "MEN'S SESSION PHOTOS",
      visible: '1',
      covers: loadCovers(28).map((img, index) => ({ id: index, img })),
      size: "cover",
      content: loadImages(28).map((img, index) => ({ id: index + 1, img })),
      reels: [],
      trailer: [],
      gridAreas: [
        "1 / 2 / 2 / 6",
        "2 / 1 / 3 / 3",
        "2 / 3 / 3 / 5",
        "2 / 5 / 3 / 7",
        "3 / 2 / 4 / 6",
        "4 / 1 / 5 / 3",
        "4 / 3 / 5 / 5",
        "4 / 5 / 5 / 7",
      ]
    },
    {
      id: 18,
      type: "photos",
      title: "TOGETHER",
      alt: "TOGETHER PHOTOS",
      visible: '1',
      covers: loadCovers(27).map((img, index) => ({ id: index, img })),
      size: "cover",
      content: loadImages(27).map((img, index) => ({ id: index + 1, img })),
      reels: [],
      trailer: [],
      gridAreas: [
        "1 / 2 / 2 / 6",
        "2 / 1 / 3 / 4",
        "2 / 4 / 3 / 7",
        "3 / 2 / 4 / 6",
        "4 / 1 / 5 / 3",
        "4 / 3 / 5 / 5",
        "4 / 5 / 5 / 7",
        "5 / 2 / 6 / 6",
        "6 / 1 / 7 / 4",
        "6 / 4 / 7 / 7",
        "7 / 1 / 8 / 4",
        "7 / 4 / 8 / 7",
      ]
    },
    {
      id: 17,
      type: "photos",
      title: "BUSINESS PHOTOS",
      alt: "BUSINESS PHOTOS",
      visible: '1',
      covers: loadCovers(26).map((img, index) => ({ id: index, img })),
      size: "cover",
      content: loadImages(26).map((img, index) => ({ id: index + 1, img })),
      reels: [],
      trailer: [],
      gridAreas: [
        "1 / 1 / 2 / 4",
        "1 / 4 / 2 / 7",
        "2 / 1 / 3 / 4",
        "2 / 4 / 3 / 7",
        "3 / 1 / 4 / 3",
        "3 / 3 / 4 / 5",
        "3 / 5 / 4 / 7",
        "4 / 1 / 5 / 3",
        "4 / 3 / 5 / 5",
        "4 / 5 / 5 / 7",
      ]
    },
    {
      id: 16,
      type: "photos",
      title: "ada",
      alt: "Ada session images",
      visible: '1',
      covers: loadCovers(25).map((img, index) => ({ id: index, img })),
      size: "cover",
      content: loadImages(25).map((img, index) => ({ id: index + 1, img })),
      reels: [],
      trailer: [],
      casts: loadCasts(25),
      gridAreas: [
        "1 / 1 / 3 / 5",
        "1 / 5 / 2 / 7",
        "2 / 5 / 3 / 7",
        "3 / 1 / 4 / 3",
        "4 / 1 / 5 / 3",
        "3 / 3 / 5 / 7",
        "5 / 2 / 6 / 6",
        "6 / 1 / 7 / 3",
        "6 / 3 / 7 / 5",
        "6 / 5 / 7 / 7",
        "7 / 1 / 9 / 5",
        "7 / 5 / 8 / 7",
        "8 / 5 / 9 / 7",
        "9 / 1 / 10 / 3",
        "9 / 3 / 10 / 5",
        "9 / 5 / 10 / 7",
        "10 / 1 / 11 / 4",
        "10 / 4 / 11 / 7",
        "11 / 1 / 13 / 5",
        "11 / 5 / 12 / 7",
        "12 / 5 / 13 / 7",
        "13 / 1 / 14 / 3",
        "14 / 1 / 15 / 3",
        "13 / 3 / 15 / 7",
        "15 / 2 / 16 / 6",
        "16 / 1 / 17 / 4",
        "16 / 4 / 17 / 7",
        "17 / 1 / 19 / 5",
        "17 / 5 / 18 / 7",
        "18 / 5 / 19 / 7",
        "19 / 1 / 20 / 3",
        "20 / 1 / 21 / 3",
        "19 / 3 / 21 / 7",
      ]
    },
    {
      id: 15,
      type: "photos",
      title: "amelia",
      alt: "Amelia session images",
      visible: '1',
      covers: loadCovers(24).map((img, index) => ({ id: index, img })),
      size: "cover",
      content: loadImages(24).map((img, index) => ({ id: index + 1, img })),
      reels: [],
      trailer: [],
      casts: loadCasts(24),
      gridAreas: [
        "1 / 2 / 2 / 4",
        "1 / 4 / 2 / 6",
        "2 / 1 / 3 / 3",
        "2 / 3 / 3 / 5",
        "2 / 5 / 3 / 7",
        "3 / 2 / 4 / 6",
        "4 / 1 / 5 / 3",
        "4 / 3 / 5 / 5",
        "4 / 5 / 5 / 7",
        "5 / 2 / 6 / 4",
        "5 / 4 / 6 / 6",
        "6 / 1 / 7 / 3",
        "6 / 3 / 7 / 5",
        "6 / 5 / 7 / 7",
        "7 / 1 / 8 / 3",
        "7 / 3 / 8 / 5",
        "7 / 5 / 8 / 7",
        "8 / 2 / 9 / 6",
        "9 / 1 / 10 / 4",
        "9 / 4 / 10 / 7",
        "10 / 1 / 11 / 3",
        "10 / 3 / 11 / 5",
        "10 / 5 / 11 / 7",
        "11 / 2 / 12 / 4",
        "11 / 4 / 12 / 6",
        "12 / 1 / 13 / 3",
        "12 / 3 / 13 / 5",
        "12 / 5 / 13 / 7",
        "13 / 2 / 14 / 4",
        "13 / 4 / 14 / 6",
        "14 / 1 / 15 / 3",
        "14 / 3 / 15 / 5",
        "14 / 5 / 15 / 7",
      ]
    },
    {
      id: 14,
      type: "photos",
      title: "reel",
      alt: "Reel session images",
      visible: '1',
      covers: loadCovers(3).map((img, index) => ({ id: index, img })),
      size: "cover",
      content: loadImages(3).map((img, index) => ({ id: index + 1, img })),
      reels: Reels,
      trailer: [],
      gridAreas: [
        "1 / 1 / 2 / 3",
        "1 / 3 / 2 / 5",
        "2 / 1 / 3 / 3",
        "2 / 3 / 3 / 5",
        "3 / 1 / 4 / 3",
        "3 / 3 / 4 / 5",
        "4 / 2 / 5 / 4",
      ],
    },
    {
      id: 13,
      type: "photos",
      title: "depth",
      alt: "Depth session images",
      visible: '1',
      covers: loadCovers(16).map((img, index) => ({ id: index, img })),
      size: "cover",
      content: loadImages(16).map((img, index) => ({ id: index + 1, img })),
      reels: [],
      trailer: [],
      casts: loadCasts(16),
      gridAreas: [
        "1 / 2 / 2 / 10",
        "2 / 1 / 3 / 3",
        "2 / 3 / 3 / 5",
        "3 / 1 / 4 / 5",
        "2 / 5 / 4 / 11",
        "4 / 2 / 5 / 10",
        "5 / 1 / 6 / 6",
        "5 / 6 / 6 / 11",
      ],
    },
    {
      id: 12,
      type: "photos",
      title: "agatta",
      alt: "Agatta session images",
      visible: '1',
      covers: loadCovers(15).map((img, index) => ({ id: index, img })),
      size: "cover",
      content: loadImages(15).map((img, index) => ({ id: index + 1, img })),
      reels: [],
      trailer: [],
      casts: loadCasts(15),
      gridAreas: [
        "1 / 2 / 2 / 6",
        "2 / 1 / 3 / 4",
        "2 / 4 / 3 / 7",
        "3 / 2 / 4 / 6",
        "4 / 1 / 5 / 4",
        "4 / 4 / 5 / 7",
        "5 / 2 / 6 / 6",
      ],
    },
    {
      id: 11,
      type: "photos",
      title: "looks",
      alt: "Looks session images",
      visible: '1',
      covers: loadCovers(14).map((img, index) => ({ id: index, img })),
      size: "cover",
      content: loadImages(14).map((img, index) => ({ id: index + 1, img })),
      reels: [],
      trailer: [],
      casts: loadCasts(14),
      gridAreas: [
        "1 / 2 / 2 / 6",
        "2 / 2 / 3 / 6",
        "3 / 1 / 4 / 3",
        "3 / 3 / 4 / 5",
        "3 / 5 / 4 / 7",
        "4 / 2 / 5 / 6",
        "5 / 1 / 6 / 4",
        "5 / 4 / 6 / 7",
        "6 / 2 / 7 / 6",
      ],
    },
    {
      id: 10,
      type: "photos",
      title: "laura",
      alt: "Laura session images",
      visible: '1',
      covers: loadCovers(22).map((img, index) => ({ id: index, img })),
      size: "cover",
      content: loadImages(22).map((img, index) => ({ id: index + 1, img })),
      reels: [],
      trailer: [],
      casts: loadCasts(22),
      gridAreas: [
        "1 / 1 / 2 / 4",
        "1 / 4 / 2 / 7",
        "2 / 2 / 3 / 6",
        "3 / 1 / 4 / 4",
        "3 / 4 / 4 / 7",
        "4 / 2 / 5 / 6",
        "5 / 1 / 6 / 4",
        "5 / 4 / 6 / 7",
        "6 / 1 / 7 / 4",
        "6 / 4 / 7 / 7",
      ]
    },
    {
      id: 9,
      type: "photos",
      title: "llis",
      alt: "Llis session images",
      visible: '1',
      covers: loadCovers(21).map((img, index) => ({ id: index, img })),
      size: "cover",
      content: loadImages(21).map((img, index) => ({ id: index + 1, img })),
      reels: [],
      trailer: [],
      casts: loadCasts(21),
      gridAreas: [
        "1 / 1 / 2 / 4",
        "1 / 4 / 2 / 7",
        "2 / 1 / 3 / 4",
        "2 / 4 / 3 / 7",
        "3 / 1 / 4 / 4",
        "3 / 4 / 4 / 7",
        "4 / 2 / 5 / 6",
        "5 / 1 / 6 / 4",
        "5 / 4 / 6 / 7",
        "6 / 1 / 7 / 4",
        "6 / 4 / 7 / 7",
      ]
    },
    {
      id: 8,
      type: "photos",
      title: "arualis",
      alt: "Arualis session images",
      visible: '1',
      covers: loadCovers(20).map((img, index) => ({ id: index, img })),
      size: "cover",
      content: loadImages(20).map((img, index) => ({ id: index + 1, img })),
      reels: [],
      trailer: [],
      casts: loadCasts(20),
      gridAreas: [
        "1 / 2 / 2 / 6",
        "2 / 2 / 3 / 6",
        "3 / 1 / 4 / 4",
        "3 / 4 / 4 / 7",
        "4 / 1 / 5 / 4",
        "4 / 4 / 5 / 7",
        "5 / 2 / 6 / 6",
        "6 / 1 / 7 / 4",
        "6 / 4 / 7 / 7",
      ]
    },
    {
      id: 7,
      type: "photos",
      title: "various",
      alt: "Various session images",
      visible: '1',
      covers: loadCovers(10).map((img, index) => ({ id: index, img })),
      size: "cover",
      content: loadImages(10).map((img, index) => ({ id: index + 1, img })),
      reels: [],
      trailer: [],
      casts: loadCasts(10),
      gridAreas: [
        "1 / 2 / 2 / 6",
        "2 / 1 / 3 / 3",
        "2 / 3 / 3 / 5",
        "2 / 5 / 3 / 7",
        "3 / 2 / 4 / 6",
        "4 / 1 / 5 / 3",
        "4 / 3 / 5 / 5",
        "4 / 5 / 5 / 7",
        "5 / 1 / 6 / 3",
        "5 / 3 / 6 / 5",
        "5 / 5 / 6 / 7",
        "6 / 1 / 7 / 4",
        "6 / 4 / 7 / 7",
      ],
    },
    {
      id: 6,
      type: "photos",
      title: "portrait",
      alt: "Portrait session images",
      visible: '1',
      covers: loadCovers(9).map((img, index) => ({ id: index, img })),
      size: "cover",
      content: loadImages(9).map((img, index) => ({ id: index + 1, img })),
      reels: [],
      trailer: [],
      casts: loadCasts(9),
      gridAreas: [
        "1 / 2 / 2 / 6",
        "2 / 1 / 3 / 3",
        "2 / 3 / 3 / 5",
        "2 / 5 / 3 / 7",
      ],
    },
    {
      id: 5,
      type: "photos",
      title: "veronica",
      alt: "Veronica session images",
      visible: '1',
      covers: loadCovers(8).map((img, index) => ({ id: index, img })),
      size: "cover",
      content: loadImages(8).map((img, index) => ({ id: index + 1, img })),
      reels: [],
      trailer: [],
      casts: loadCasts(8),
      gridAreas: [
        "1 / 1 / 3 / 5",
        "1 / 5 / 2 / 7",
        "2 / 5 / 3 / 7",
        "3 / 1 / 5 / 4",
        "3 / 4 / 5 / 7",
        "5 / 1 / 7 / 4",
        "5 / 4 / 7 / 7",
        "7 / 2 / 9 / 6",
        "9 / 1 / 11 / 4",
        "9 / 4 / 11 / 7",
        "11 / 1 / 13 / 4",
        "11 / 4 / 13 / 7",
        "13 / 2 / 15 / 6",
        "15 / 1 / 16 / 3",
        "15 / 3 / 16 / 5",
        "15 / 5 / 16 / 7",
        "16 / 1 / 17 / 3",
        "16 / 3 / 17 / 5",
        "16 / 5 / 17 / 7",
        "17 / 2 / 19 / 6",
        "19 / 1 / 20 / 3",
        "19 / 3 / 20 / 5",
        "19 / 5 / 20 / 7",
        "20 / 1 / 21 / 3",
        "20 / 3 / 21 / 5",
        "20 / 5 / 21 / 7",
        "21 / 2 / 23 / 6",
        "23 / 1 / 24 / 3",
        "23 / 3 / 24 / 5",
        "23 / 5 / 24 / 7",
        "24 / 1 / 25 / 3",
        "24 / 3 / 25 / 5",
        "24 / 5 / 25 / 7",
      ],
    },
    {
      id: 4,
      type: "photos",
      title: "sabine",
      alt: "Sabine session images",
      visible: '1',
      covers: loadCovers(7).map((img, index) => ({ id: index, img })),
      size: "cover",
      content: loadImages(7).map((img, index) => ({ id: index + 1, img })),
      reels: [],
      trailer: [],
      casts: loadCasts(7),
      gridAreas: [
        "1 / 2 / 2 / 6",
        "2 / 2 / 3 / 6",
        "3 / 2 / 4 / 6",
        "4 / 1 / 5 / 4",
        "4 / 4 / 5 / 7",
        "5 / 2 / 6 / 6",
      ],
    },
    {
      id: 3,
      type: "photos",
      title: "kate",
      alt: "Kate session images",
      visible: '1',
      covers: loadCovers(6).map((img, index) => ({ id: index, img })),
      size: "cover",
      content: loadImages(6).map((img, index) => ({ id: index + 1, img })),
      reels: [],
      trailer: [],
      casts: loadCasts(6),
      gridAreas: [
        "1 / 1 / 2 / 6", 
        "1 / 6 / 2 / 13",
        "2 / 3 / 3 / 11", 
        "3 / 3 / 4 / 11",
        "4 / 1 / 5 / 7",
        "4 / 7 / 5 / 13",
      ],
    },
    
    {
      id: 2,
      type: "media",
      title: "etude",
      alt: "Etude session images",
      visible: '1',
      covers: loadCovers(4).map((img, index) => ({ id: index, img })),
      size: "cover",
      content: [],
      reels: [],
      trailer: 'https://vimeo.com/866926768',
      desc: loadDescriptions(2),
      casts: loadCasts(4),
      gridAreas: []
    },
    {
      id: 1,
      type: "photos",
      title: "impress",
      alt: "Impress session images",
      visible: '1',
      covers: loadCovers(1).map((img, index) => ({ id: index, img })),
      size: "cover",
      content: loadImages(1).map((img, index) => ({ id: index + 1, img })),
      reels: [],
      trailer: [],
      casts: loadCasts(1),
      gridAreas: [
        "1 / 2 / 2 / 6",
        "2 / 1 / 3 / 4",
        "2 / 4 / 3 / 7",
      ],
    },
  ];
};